#!/bin/bash

if [ ${#@} == 0 ]; then
    echo "Usage: $0 APIKey file"
    echo "* APIKey: Your Mailgun API key"
    echo "* file: The CSV file to read from. First column are From: email addresses. All other columns are the emails to forward to."
fi

while IFS='' read -r line || [[ -n "$line" ]]; do
  emails=($line)
  numemails=${#emails[@]}
  fromEmail=${emails[0]}
  if test "${fromEmail: -1}" == ","
  then
    fromEmail=${fromEmail%?} # Trim trailing comma.
  fi
  command="curl -s --user '$1' \
      https://api.mailgun.net/v3/routes \
      -F description='Generated by mailgun.sh' \
      -F priority=0 \
      -F expression='match_recipient(\"$fromEmail\")'"

  for ((i=1; i < $numemails; i++))
  do
    email=${emails[$i]}
    if test "$numemails" -gt "2" && test "${email: -1}" == ","
    then
      email=${email%?} # Trim trailing comma.
    fi
    # echo "$email"
    command+="      -F action='forward(\"$email\")'"
  done

  echo $command
  # eval $command

done < "$2"
